////
Copyright 2018 Yahoo Japan Corporation.
Licensed under the terms of the MIT license.
See LICENSE in the project root.
////

[[comparing]]
= Solr/ElasticSearch との機能比較
include::_include.adoc[]

このセクションでは、Vespa と他の検索エンジンを比べて、
具体的にどのような差異があるのか見ていきます。

[WARNING]
====
著者の個人的な見解がかなり含まれます。
====

[NOTE]
====
http://vespa.ai/[Vespaの公式ページ]
の下の方にも機能比較表があります。
====

ここでは、比較対象として
http://lucene.apache.org/solr/[Solr]
と
https://www.elastic.co/jp/products/elasticsearch[ElasticSearch]
の2つを取り上げます。
Solr と ElasticSearch は共に Lucene をコアとする検索エンジンで、
世界的にも多くの利用実績がある代表的な OSS の一つです。

[NOTE]
====
チュートリアルには `appendix` にSolrとElasticSearchのDockerコンテナの設定があります。
それぞれのディレクトリに配置された `boot.sh` を実行することでVespaと同じドキュメントを含むSolrおよびElasticSearchを起動できます。
詳しいコマンドは `appendix` にある `README.md` を参照してください。
====

[[comparing_update]]
== スキーマと更新

[[comparing_update_dynamic]]
=== 動的フィールド

Solr/ElasticSearch と Vespa のスキーマ定義を比較したとき、
大きな違いの一つとして動的フィールドのサポートの有無があります。

Solr では `dynamic fields` を、
ElasticSearch では `dynamic templates` を使ってインデックスされたフィールド名に応じて動的にフィールドを追加することができます。
この機能によって、Solr/ElasticSearch ではスキーマに縛られにくい柔軟なインデクシングを可能としています。
特に、ElasticSearch では
https://www.elastic.co/guide/en/elasticsearch/reference/current/object.html[Object datetype]
のようにかなり自由なデータをインデクシングできるのが特徴です。

一方、Vespa では前述のような動的フィールドに対応する機能は現状では提供されていません。
そのため、ユーザは事前にスキーマ設計をしっかりと行うことが求められます。

サービスとして検索エンジンを使う場合、
一般的にスキーマ設計を行うはずなので双方であまり差異はありませんが、
データストアとして検索エンジンを使う場合は、
動的フィールドが可能な Solr/ElasticSearch の方が柔軟性が高いと考えられます。

[NOTE]
====
データストア・アナリシス的な用途なら
https://www.elastic.co/jp/products[Elastic Stack]
が有名かと思います。
====

[[comparing_update_type]]
=== データ型

Vespa、Solr/ElasticSearch ともに基本的なデータ型については大きな差異はありません。
2つで動作が大きく異なるケースとして、配列のような多次元の値を扱う場合があげられます。

Vespa では
<<2_config.adoc#config_file_searchdefinitions,searchdefinitions>>
で述べたように、`array` と `weightedset` という2つの型をサポートしています。
Vespa での複数値は、
<<5_ranking.adoc#ranking_expression_feature_attribute,attribute>>
といった関数を用いてインデックスやキーで各値に個別アクセスができ、
値の順序 (例えば階層構造とか) に意味を持たせることができます。
また、Vespa では
<<5_ranking.adoc#ranking_other_tensor,テンソルを用いたスコア計算>>
で述べたテンソル型という高次元のデータ型を保持することができ、
近年注目を集めている分散表現やディープライーニングといった先進技術との親和性が高いことも大きなポイントです。

一方、Solr/ElasticSearch の場合、配列型以外については設計を工夫する必要があります。
チュートリアルの例では、前述の動的フィールドを用いてマッピングを行うことで Vespa の `weightedset` の代替としています。
この方法では、キーとなる新しい値が登録されるたびに裏側では新しいフィールドが定義されることとなるため、
キーのバリエーションが非常に多いケースを扱うことが困難です。
また、高次元ベクトルを検索で扱う場合に、Solr/ElasticSearch ではまだ適切なデータ型がないように感じます。

[TIP]
====
Solr/ElasticSearch の配列は、インデックス上では投入順序が保持されないという特徴があります。
これは、内部で利用している Lucene の `docValues` というデータストアが、
複数値を登録する時にソートして値を保持するという制約があるためです。
そのため、Vespa のようにインデックス指定で値を取得する、ということができません。
====

[NOTE]
====
Solr/ElasticSearch でも拡張フィールドを独自実装すれば、`weightedset` のような型を作ることは一応可能です。
ただし、スコア計算との連携なども考えた場合、ランキング部分についても拡張が必要になります。
====

[[comparing_update_realtime]]
=== リアルタイム性

Solr/ElasticSearch の基盤となっている Lucene では、
`softCommit` と `hardCommit` という2つのコミットによってインデックスを管理します。
前者は更新内容を検索できるようにするもの、後者は更新内容をディスクに永続化するものに対応します。
Solr/ElasticSearch では、この `softCommit` の間隔を制御することで Near Real Time (NRT) 検索を実現しています (
https://lucene.apache.org/solr/guide/7_2/near-real-time-searching.html[Solr]、
https://www.elastic.co/guide/en/elasticsearch/guide/current/near-real-time.html[ElasticSearch]
)。
より高いリアルタイム性が必要な場合、この `softCommit` の間隔をチューニングすることになりますが、
`softCommit` では `Searcher` と呼ばれる検索を担当するインスタンスの再生成が走るため、
実行にある程度のコストがかかります。
そのため、`softCommit` の頻度が検索などのパフォーマンスに影響を与え、
性能要件によっては短い時間を設定することが困難な場合が多いです。

Vespa では公式ドキュメントの
http://docs.vespa.ai/documentation/features.html[Features]
や
http://docs.vespa.ai/documentation/content/consistency.html[Vespa consistency model]
で述べられているように、
更新リクエストのレスポンスが返ったタイミングで検索の対象となるように設計されています。
そのため、ドキュメント更新のリアルタイム性が非常に高い検索エンジンといえます。

[WARNING]
====
Vespa のインデクシングの中身の詳細については公式ドキュメントが特になかったため、
ここでは上記 Vespa のドキュメントでの謳い文句と運用での経験ベースに話をしています。

Vespa のインデックスのざっくりとした流れは
http://docs.vespa.ai/documentation/performance/sizing-search.html[Vespa search sizing guide]
の `Search/Content Node` で議論されており、
新規ドキュメントはオンメモリ上のインデックス (`memory index`) に追加され、
サイズや時間経過を条件に適宜ディスク上のインデックスに書き出される、という動作をします。
====

[[comparing_search]]
== 検索周り

[[comparing_search_aggregation]]
=== 集約処理

単純な検索機能については Vespa と Solr/ElasticSearch では大きな差はないですが、
集約処理については Vespa と Solr/ElasticSearchで 差異があります。

検索結果を羅列する `grouping` という観点では、
Vespa は Solr/ElasticSearch に比べて高機能です。
Vespa は
<<4_search.adoc#search_grouping,グルーピング検索>>
で紹介したように、
http://docs.vespa.ai/documentation/reference/grouping-syntax.html[Query result grouping reference]
に記載された DSL を用いて集約処理の動作を定義しますが、
Solr/ElasticSearch ではできない
「グルーピングのグルーピング」
のような多階層のグルーピングをサポートしています。
そのため、例えばショッピング検索を例にとると、
「あるストアの商品をさらにカテゴリ毎にグループ分けしてそれぞれ上位3件を表示」
のような細分化された検索結果を得ることが可能です。

各グループの統計値といった特定の側面を計算する `faceting` という観点では、
Vespa と Solr/ElasticSearch でそこまで大差はない (もしくは Solr/ElasticSearch の方が上？) と感じます。
前述の DSL のお陰で Vespa は `faceting` でも様々な集約条件を定義できます。
一方、Solr では
https://lucene.apache.org/solr/guide/7_2/streaming-expressions.html[Streaming Expressions]
を用いることで、検索結果をストリーミング処理の要領で細かく加工することが可能です。
また、ElasticSearch も
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations.html[Aggregations]
で紹介されているような多くの集約処理があったり、
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html[Scripting]
で細かい調整が可能だったりと高機能です。

[[comparing_search_advanced]]
=== 高度な検索機能

<<4_search.adoc#search_other,その他の検索>>
で紹介したように、
WAND 検索、ブーリアンインデックス、ストリーミング検索
と Vespa には Solr/ElasticSearch にはない検索機能があります。

[NOTE]
====
位置検索は Solr/ElasticSearch にもあります。
====

単純な全文検索ではなかなか使うタイミングがない機能ですが、
レコメンド、広告、メールなど具体的にターゲットを絞った場合、
これらの機能の恩恵を受けられるケースがあるかもしれません。

[[comparing_ranking]]
== ランキング

[IMPORTANT]
====
ランキングは OSS で利用できる範囲での比較になります。
そのため、Solr の有償プロダクトである
https://lucidworks.com/products/[Fusion]
や、ElasticSearch の有償の
https://www.elastic.co/jp/products/x-pack[X-PACK]
で提供されている機能については対象外としています。
====

[[comparing_ranking_phase]]
=== フェーズ分け

検索エンジンのコア機能を使って任意のスコア式を記述する場合、
Solr は
https://lucene.apache.org/solr/guide/7_2/function-queries.html[FunctionQuery]
を、ElasticSearch は
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#score-functions[FunctionScoreQuery]
を用いてスコアを定義します。
また、最近では上位の結果をリランキングするプラグインとして Solr と ElasticSearch それぞれで
LTR (Learning To Rank) プラグインが提供されています (
https://lucene.apache.org/solr/guide/7_2/learning-to-rank.html[Solr]、
http://elasticsearch-learning-to-rank.readthedocs.io/en/latest/[ElasticSearch]
)。

[TIP]
====
Solr ではこれに加えて
https://lucene.apache.org/solr/guide/7_2/query-re-ranking.html[ReRakQParserPlugin]
と `FunctionQuery` を組み合わせる方法もあります。
====

Vespa の
<<5_ranking.adoc#ranking_phase,ランキングの流れ>>
と対応させると、
Solr の `FunctionQuery` および ElasticSearch の `FunctionScoreQuery` が `first-phase` に、
LTRプラグインが `second-phase` に対応します。

このように、Solr と ElasticSearch では2つのフェーズのランキングが別の機能として提供されます。
そのため、2つのフェーズでスコア式を記述する場合、別々に定義を書かなくてはならないというのがネックです。
それに対して、Vespa は `rank-profile` に全てまとめて定義できるため、
ランキングの定義は Vespa の方がスッキリしています。

[[comparing_ranking_dsl]]
=== 記述の自由度

単純な記述の自由度という観点では、
最も自由度が高いのは
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html[Scripting]
を用いて Groovy ライクに書けるElasticSearchの `Function Score Query` かと思います。
ただし、`Scripting` ではいわゆる素性が扱えないため、
高度なモデルを定義したい場合にネックになると考えられます。

[TIP]
====
`Scripting` は
http://asm.ow2.org/[ASM]
を用いてバイトコードを動的に生成することで高速動作させています。
====

一方、Solr と ElasticSearch の LTR プラグインでは、
検索クエリを素性として定義できるため、より精度の高いモデルを定義できます。
ただ、こちらはデフォルトで利用できるモデルの型が線形モデルとアンサンブル木に限定されており、
チュートリアルの `price_boost` のような独自の数式を書きたい場合は、
別途対応するモデルを実装する必要があるというのが難点です。

Vespa はランク式を DSL として提供しつつ、
<<5_ranking.adoc#ranking_expression_feature,組み込み素性>>
で紹介したように様々なランク素性が利用できるため、自由に高度なモデルの記述が可能です。
また、検索クエリを使う LTR プラグインと異なり、これらランク素性はコードとして実装されているため動作が速いのも特徴です。
ただし、組み込みの素性以外を使いたいという場合、`rank-profile` のマクロとして数式の定義はできますが、
全く新しい素性を実装して追加するためには検索コアの実装に手を加える必要があり、難易度が高いです。

[[comparing_ranking_advanced]]
=== 高度なランキング

<<5_ranking.adoc#ranking_other_tensor,テンソルを用いたスコア計算>>
で紹介したテンソルへの対応は、Vespa がもつ非常に強力な機能です。
内積や行列演算は state-of-the-art な手法をランキングで用いたい場合に必要になる機能なので、
検索エンジンが標準でそれをサポートしている意味は大きいです。

また、
<<4_search.adoc#search_other_wand,WAND 検索>>
もランキングの視点で見ると疎ベクトルの内積計算に対応しており、
Vespa の持つ高度なランキング機能の一つと捉えることができます。

WAND 検索については、
Solr/ElasticSearch でも payload でテキストの単語に重みを埋め込み、
検索クエリにブースト値を付与してスコア計算に組み込めば似たようなことは可能です。
ただし、WAND 検索のような賢い枝刈りアルゴリズムがないため、Vespa より速度がでないと思います。

[NOTE]
====
最近では Solr コミュニティで
https://deeplearning4j.org/[DL4J]
を LTR プラグインに組み込もうという動きもあります (
https://issues.apache.org/jira/browse/SOLR-11838[SOLR-11838]
)。
====

[[comparing_scalability]]
== スケーラビリティ

[[comparing_scalability_distrib]]
=== 分散インデクシング

Vepsa は
<<6_clustering.adoc#clustering_distrib,ドキュメントの分散>>
でも述べたように、ドキュメントを `bucket` という細かい粒度で分散させるのが特徴で、
ここは Solr/ElasticSearch と大きく異なる点の一つです。

Solr/ElasticSearch では、クラスタ上でのインデックスの分割数 (シャード数) を事前に決めて分散インデクシングを行います。
このシャード数は、一度決めると容易にその数を変更することができず、
変更する場合はシャードの分割やインデックスの再構築が必要となります。

一方、Vespa は `bucket` というより細かい粒度でドキュメントを管理しており、
その分割数も状況によって増減します。
そのため、ユーザはインデックスの冗長数 (Solr/ElasticSearch のレプリカ数) だけを意識すればよく、
分散インデクシングの管理が非常に容易かつ効率的に行うことができます。

ドキュメントを細かい粒度で分散させることは、障害時のパフォーマンスという観点でも有意性があります。
Solr/ElasticSearch の場合、特定のノードがダウンすると、
本来そのノードが処理するはずだったリクエストを対応するレプリカを持つノード群が肩代わりします。
そのため、障害時に特定のノードのリクエスト数が `1 + 1/#replicas` 倍に増加することになります。
一方、Vespa の場合、特定のノードがダウンしたとしても、対になる `bucket` はクラスタ全体に分散しているため、
ダウンしたノードのリクエストをクラスタ全体でカバーすることができ、
リクエスト数の増加を `1 + 1/#nodes` 倍に抑えることができます。
基本的に `#nodes > #replicas` となるため、障害時の負荷増加は Vespa の方が小さくなります。

[[comparing_scalability_node]]
=== ノードの追加・削除

クラスタへのノードの追加・削除も、
Vespa では非常に簡単に行うことができます。

Solr/ElasticSearch の場合、前述のようにシャード数が変更できないため、
ノードの増減にあわせてシャード/レプリカ単位での再分配を行うことになります。
この作業は、ElasticSearch の場合、再分配は自動で行われますが、Solr の場合は現状手作業で行う必要があります。
シャード自体の分割が困難なため、ノード追加・削除が発生した場合、
場合によってはシャード数を再設計して再インデックスする必要があります。

Vespa では、
<<6_clustering.adoc#clustering_setup_deploy,クラスタ設定の反映>>
の例で示したように、`services.xml` と `hosts.xml` に追加・削除するノードの情報を追記して反映させるだけで、
Vespa が `bucket` の再分配を行ってくれます。
また、Solr/ElasticSearch のようにシャード数を気にする必要もないため、
カジュアルにノードの増減を行うことが可能です。

[[comparing_extensibility]]
== 拡張性

[[comparing_extensibility_language]]
=== 多言語対応

多言語対応という点では、現状 Vespa は Solr/ElasticSearch に比べると大きく差があります。

Solr/ElasticSearch は世界的に利用実績があるため、現状で多くの言語をサポートしています。
また、Solr/ElasticSearch の言語処理は、
入力文字列の1文字1文字に変換を加える `CharFilter`、
文字列をトークン分けする `Tokenizer`、
トークン毎に変換を加える `TokenFilter`
の3つのクラスの組み合わせによって定義されます (
https://lucene.apache.org/solr/guide/7_2/understanding-analyzers-tokenizers-and-filters.html[Solr]、
https://www.elastic.co/guide/en/elasticsearch/reference/current/analyzer-anatomy.html[ElasticSearch]
)。
そのため、これらの組み合わせ方によって言語処理フローを柔軟に構築できるというのも特徴の一つです。

一方、Vespa は OSS としてまだ若いこともあり、公式でサポートしている言語は今のところ英語圏に限られています。
Vespa では
http://docs.vespa.ai/documentation/linguistics.html[Linguistics]
というクラスを拡張することで対応言語を増やすことができます。
Solr/ElasticSearch とは異なり、
Vespa ではステミングや正規化といった処理も `Lingusitics` の中に内包させます。
幸い、今回使用した `KuromojiLinguistics` のように、
既存のパッケージを組み合わせれば対応自体はそこまで難しくはないので、
今後ユーザが増えていって多言語対応の差自体が埋まっていくことを期待します。

[[comparing_extensibility_plugin]]
=== プラグインの追加

Solr/ElasticSearch は、
世の中にサードパーティ製のプラグインがたくさんあることからも分かるように、
拡張性が高い検索エンジンとなっています。
また、Solr/ElasticSearch は Pure Java で実装された検索エンジンなので、
機能開発の敷居も比較的低いといえます。

Vespa でプラグインを追加する場合は、基本的に
<<2_config.adoc#config_file_services_container,container>>
にプラグインを追加していく形になります。
典型的な拡張は、
検索リクエスト/レスポンスの加工を行う `Searcher`、
更新リクエストの加工を行う `DocumentProcessor` の追加です。
これらはサーブレット・フィルタのようにチェインさせてパイプライン処理させるように利用します(
http://docs.vespa.ai/documentation/component-types.html[Container component types]
)。
また、Vespa の `container` は
http://docs.vespa.ai/documentation/jdisc/[JDisc]
(Java Data Intensive Serving Container) というフレームワークの上で動作しており、
内部で独自のサーバを立てたり、DI コンテナでインジェクトするインスタンスを差し替えたりと、
色々自由に動作を変えることができます。

[TIP]
====
前述の `Linguistics` も JDisc の DI コンテナ経由で独自実装をインジェクトすることで動作を差し替えています。
====

一方、Vespa の検索コアは
http://docs.vespa.ai/documentation/proton.html[proton]
と呼ばれる C++ のパッケージとなっており、
こちらに機能を追加したい場合はコードを実装して再ビルドする必要があります。
そのため、検索コアの深いところまで手を加えたい場合、
Vespa は Solr/ElasticSearch に比べると実装難易度が高いです。

[[comparing_summary]]
== まとめ

ここまで述べてきた Vespa と Solr/ElasticSearch の特徴を、
http://vespa.ai/[公式サイト]
の表のようにまとめると以下のようになります。

[options="header", cols="1,1,1,3a"]
|====
^| 特徴 ^| Vespa ^| Solr/ElasticSearch ^| 備考
^| データ解析 ^| ☆ ^| ☆☆☆ |
* Solr/ElasticSearch は動的フィールドが使える
* Solr/ElasticSearch の方が解析処理が充実してる印象
* Elastic Stack のように周辺パッケージも充実
^| 全文検索 ^| ☆☆☆ ^| ☆☆ |
* 両方とも検索の基本機能はカバー
* Vespa の方がグルーピング処理が強力
* インデクシングが Vespa の方が優秀
^| ランキング ^| ☆☆☆ ^| ☆ |
* Vespa は標準機能でランキングをフルサポート
* フェーズ制御が Vespa の方がしっかりしてる
* WAND 検索やテンソルなど Vespa の方が機能が先進的
^| スケーラビリティ ^| ☆☆☆ ^| ☆☆ |
* Vespa の方が分散粒度が細かく柔軟性が高い
* ノード増減時のインデックス調整が Vespa の方が楽
* Solr/ElasticSearch はシャード数が変更しづらい
^| 拡張性 ^| ☆☆ ^| ☆☆☆ |
* Solr/ElasticSearch の方が敷居は低め
* Vespa も自由度は高いが検索コアがいじりにくい
* 多言語対応などの既存遺産の差が大きい
|====

見解としては公式サイトでの表と同じで、全文検索がしたいなら Vespa はよい選択肢になると思います。
逆に、データ解析での利用を検討している場合は、Elastic Stack のようなパッケージを利用した方が効率的かと思います。

機能面では、まずランキング機能が Solr/ElasticSearch と比べてかなり先進的で、
特にテンソルが扱えることで、近年話題の Deep Learning 系の技術を取り込める点は大きな強みです。
また、ドキュメント分散の仕組みが賢く、スケールアウトが容易な点も、
特に大規模なクラスタを組むようなケースで大きなポイントになるかと思います。

一方、拡張性という観点では、OSS としてまだ若いこともあり、
Solr/ElasticSearch に比べてサードパーティ製のプラグインなどのオプションが少ないところはネックかと思います。
Vespa 自体の拡張性は JDisc のおかげで非常に高いのですが、
個人的には検索コアに手が入れにくいところが気になる部分で、
このため拡張性については公式サイトと優劣を逆につけています。