#!/bin/bash
#
# Copyright 2018 Yahoo Japan Corporation.
# Licensed under the terms of the MIT license.
# See LICENSE in the project root.
#

set -eu


function usage {
    cat <<EOF 1>&2
usage: $0 FEED_DATA

NOTE: you need root privilege to execute this script due to "docker-compose".

ex) feed "book-data-put.json" (i.e., "sample-apps/feed/book-data-put.json") into Vespa.
$ $0 book-data-put.json
EOF
}

function feed {
    feed_data="/vespa-sample-apps/feed/$1"
    sudo docker-compose exec vespa1 /bin/bash -c "/opt/vespa/bin/vespa-feeder < ${feed_data}"
    return $?
}


if [ $# -eq 0 ]; then
    usage
    exit 1
fi

# move to project directory to refer docker-compose.yml
PROJ_DIR=$(cd $(dirname $0)/..; pwd)
cd ${PROJ_DIR}

feed_data=`basename $1`
if [ ! -f "${PROJ_DIR}/sample-apps/feed/${feed_data}" ]; then
    echo "<ERROR> failed to find \"${PROJ_DIR}/sample-apps/feed/${feed_data}\"" 1>&2
    exit 1
fi
feed ${feed_data}

exit $?
